project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "assignment_gretl.qmd"
    - "assignment_r.qmd"
website:
  title: "OEKA201AssignmentHJ"
  navbar:
    left:
      - text: "Index"
        href: index.qmd
      - text: Exercises using Gretl
        href: assignment_gretl.qmd
      - text: Exercises using R
        href: assignment_r.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    # you will need to add additonal stuff here assignment part 3
  docx:
    toc: true
    # you will need to add additonal stuff here assignment part 3
  pdf:
    toc: true
    number-sections: true
    # you will need to add additonal stuff here assignment part 3
  epub:
    toc: true
    toc-depth: 3
    # you will need to add additonal stuff here assignment part 3
bibliography: ref.bib







